### ISSUE TITLE
Issue with multiple instruments score

### ISSUE THREAD

**Issue by LucasPa** [salvador-pena/addMetronomePart#1]
Hi,

Thanks for this nice very useful plugin. It works correctly when I use it on a music sheet with a single instrument. But I tried to use it on a musescore file with multiple instruments from my big band. The "Wood Blocks" part is added but is only filled with whole rests.

Best,

Lucas

**Comment by salvador-pena** [comment]
Hi, 
Could you provide a sample score (.mscz or .mscx) to reproduce the issue?

**Comment by LucasPa** [comment]
Hi,

Unfortunately I experienced the problem with a score that I'm not supposed
to share...

Best,

Lucas

**Comment by salvador-pena** [comment]
Can't repro.

**Comment by salvador-pena** [comment]
Can't repro.

**Comment by salvador-pena** [comment]
Can't repro.
