### ISSUE TITLE
How to install/enable for Musescore 4

### ISSUE THREAD

**Issue by michellehawkins** [salvador-pena/addMetronomePart#4]
Hi,

This is my first time using Musescore. I downloaded Musescore 4 just last week, but I've been learning a lot quickly. Can you make a video detailing how to install or enable this metronome plugin for Musescore 4? Their handbook claims that it is in the list of plugins that "have been ported to or created for Mu4". I hope that means that it is ready to use now. Thanks for your support.

-Michelle

p.s. The only info for how to install plugins routes back to Musescore 3. I don't want to have to download an additional, older version of Musescore in order to get this to work.

**Comment by salvador-pena** [comment]
Hi,

I am not able to create a video from an english localization,
however you can follow the install guide of MuseScore3 since the steps are quite the same for MuseScore4, the only difference is folder name.
