### ISSUE TITLE
Musescore 4.0.2 in page layout: page up and page down don't shift only horizontal 

### ISSUE THREAD

**Issue by HansJazz22** [salvador-pena/addMetronomePart#5]
I ame new in GitHub
Have no Idea how to post a issue.
Please help me if this the wrong place
Thank you

I use a labtop (2 in 1) in portret mode.
Use page lauout.
adjuist the screen that a whole page fill the screen.
- the page down shifts not only horizontal but also vertical
- key home and end work as I expext

0- When I use muscore 3 it work exelent
0- In this way Musescore can work with a page turner (the professional way of viewing a score)
0- By the way (the problem occure also in landscape mode)

**Comment by salvador-pena** [comment]
For support and bugs regarding MuseScore go to [the forum](https://musescore.org/en/forum).

**Comment by salvador-pena** [comment]
Closing as it is not related to the plugin.

**Comment by salvador-pena** [comment]
Closing as not related to the plugin.
